/***********************************************************************/
/*                                                                     */
/*  FILE        :test123.c                                             */
/*  DATE        :Mon, Jan 22, 2024                                     */
/*  DESCRIPTION :main program file.                                    */
/*  CPU GROUP   :2B                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.15).    */
/*                                                                     */
/***********************************************************************/

