extern unsigned far char * font;
extern unsigned char half_sec_flag;
extern unsigned int half_sec_ctr;
//extern unsigned char serial_data_flag;
//extern unsigned char serial_start_flag;
//extern unsigned char max_serial_ctr;
//extern unsigned char serial_data_ctr;
//extern unsigned int serial_timeout_ctr;
//extern unsigned char serial_timeout_flag;
extern signed char gsc_i2c_retsts;
extern unsigned int key_timeout_ctr;
extern unsigned char key_timeout_flag;
extern unsigned char continuous_mode_flag;
extern unsigned char key_status_flag;
extern unsigned char key_press_flag;
extern unsigned int firstkey_bounce_ctr;
extern unsigned int secondkey_bounce_ctr;
extern unsigned int thirdkey_bounce_ctr;
extern unsigned char firstkey_release_flag;
extern unsigned char secondkey_release_flag;
extern unsigned char thirdkey_release_flag;
extern unsigned char first_key_flag;
extern unsigned char second_key_flag;
extern unsigned char third_key_flag;
extern unsigned char first_press_flag;
extern unsigned char second_press_flag;
extern unsigned char third_press_flag;
extern unsigned int first_contpress_ctr;
extern unsigned int second_contpress_ctr;
extern unsigned int value_count_loc;
//extern unsigned char key_beep_flag;
//extern unsigned int key_beep_counter;
extern unsigned int min_y;
extern unsigned int max_y;
extern unsigned char temp_disp_array[40];
extern unsigned char eeprom_error_code;
extern unsigned char data_read_flag;
extern unsigned char data_save_flag;
//extern unsigned long hv_signal_value;
//extern unsigned long hv_anode_value;
//extern unsigned long hv_cathode_value;
//extern unsigned long bleeder_anode_value;
//extern unsigned long bleeder_cathode_value;
//extern unsigned long filament_signal_value;
//extern unsigned long short_filament_value;
//extern unsigned long long_filament_value;
extern unsigned int buf_x;
extern unsigned int buf_y;
extern unsigned char cur_font_height;
//extern unsigned char tft_disp_array[5][26];
extern unsigned char pc_timeout_flag;
extern unsigned int pc_timeout_ctr;
extern unsigned char pc_data_ctr;
extern unsigned char pc_data_recd;
extern unsigned char pending_pcdata_bytes;
//extern unsigned long tmphv_anode_value;
//extern unsigned long tmphv_cathode_value;
//extern unsigned long tmpbleeder_anode_value;
//extern unsigned long tmpbleeder_cathode_value;
//extern unsigned long no_of_samples;
//extern unsigned long tmpshort_filament_value;
//extern unsigned long tmplong_filament_value;
extern unsigned char chr_bit_height;
extern unsigned char chr_bit_width;
extern unsigned long hvt_slno_loc;

extern unsigned char adc_read_flag;
extern unsigned long adc_array_ctr;
extern unsigned long max_adc_arrayctr;
extern unsigned long hv_input_array[ADC_ARRAY_CONST]; 
extern unsigned long hv_cathode_array[ADC_ARRAY_CONST]; 
extern unsigned long hv_anode_array[ADC_ARRAY_CONST]; 
extern unsigned long bleeder_anode_array[ADC_ARRAY_CONST]; 
extern unsigned long bleeder_cathode_array[ADC_ARRAY_CONST]; 
extern unsigned long filament_input_array[ADC_ARRAY_CONST]; 
extern unsigned long long_filament_array[ADC_ARRAY_CONST]; 
extern unsigned long short_filament_array[ADC_ARRAY_CONST]; 
extern unsigned long readhv_input_value;
extern unsigned long readhv_anode_value;
extern unsigned long readhv_cathode_value;
extern unsigned long readbleeder_anode_value;
extern unsigned long readbleeder_cathode_value;
extern unsigned long readfilament_input_value;
extern unsigned long readshort_filament_value;
extern unsigned long readlong_filament_value;
extern unsigned long hv_input_value;
extern unsigned long hv_anode_value;
extern unsigned long hv_cathode_value;
extern unsigned long bleeder_anode_value;
extern unsigned long bleeder_cathode_value;
extern unsigned long filament_input_value;
extern unsigned long short_filament_value;
extern unsigned long long_filament_value;
extern unsigned char hv_input_flag;
extern unsigned long adc_avg_ctr;
extern unsigned char adc_timeout_flag;
extern unsigned char adc_timeout_ctr;
extern unsigned char discard_adc_flag;
extern unsigned char cur_machine_state;
extern unsigned char shift_machine_state;




extern struct pointer_info pointer_info_buffer;;
extern struct test_data test_data_buffer;
extern struct cctalk_data pc_recd_buffer;
extern struct dac_info dac_info_buffer;

extern const unsigned short CCITT_CRC_LookupTable[256];



extern const unsigned char company_name[];
extern const unsigned char firmware_version[];
extern const unsigned char model_name[];
extern const unsigned char hv_turns_text[];
extern const unsigned char hv_input_text[];
extern const unsigned char anode_hv_text[];
extern const unsigned char cathode_hv_text[];
extern const unsigned char bleeder_turns_text[];
extern const unsigned char bleeder_anode_text[];
extern const unsigned char bleeder_cathode_text[];
extern const unsigned char filament_turns_text[];
extern const unsigned char filament_input_text[];
extern const unsigned char large_filament_text[];
extern const unsigned char small_filament_text[];
extern const unsigned char filament_changed_text[];
extern const unsigned char test_passed_text[];
extern const unsigned char test_failed_text[];
extern const unsigned char main_menu_text[];
extern const unsigned char main_menu_text1[];
extern const unsigned char vpk_text[];
extern const unsigned char vac_text[];
extern const unsigned char vdc_text[];
extern const unsigned char mvdc_text[];
extern const unsigned char pass_text[];
extern const unsigned char fail_text[];
extern const unsigned char plus_symbol[];
extern const unsigned char minus_symbol[];
extern const unsigned char menu_name_text[];
extern const unsigned char filnot_connected_text[];


extern const unsigned char press_key_text[];

extern const unsigned char arial_narrow_bold12[];
extern const unsigned char arial_narrow_bold14[];
extern const unsigned char arial_narrow_bold16[];
extern const unsigned char arial_narrow_bold18[];
extern const unsigned char arial_narrow_bold20[];
extern const unsigned char arial_narrow_bold24[];

extern const unsigned char arial_narrow_bold12SI[];
extern const unsigned char arial_narrow_bold16SI[];
extern const unsigned char arial_narrow_bold20SI[];
