/***********************************************************************/
/*                                                                     */
/*  FILE        :firm.c                                                */
/*  DATE        :Thu, Jul 08, 2010                                     */
/*  DESCRIPTION :set the firm area of OnChipDebuggers.                 */
/*  CPU GROUP   :2A                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.18).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
/*********************************************************************
*
* Device     : R8C/Tiny/2x
*
* File Name  : firm.c
*
* Abstract   : Set the firm area of OnChipDebuggers.
*
* History    : 1.20  (2009-03-17)
*
* Copyright (C) 2009 (2010) Renesas Electronics Corporation.
* and Renesas Solutions Corporation. All rights reserved.
*
*********************************************************************/
#include "typedefine.h"
#ifdef __E8__

#pragma section bss FirmArea
_far _UBYTE _firmarea[0x800U];

#endif

