/***********************************************************************/
/*                                                                     */
/*  FILE        :HVTJ.c                                                */
/*  DATE        :Thu, Jul 08, 2010                                     */
/*  DESCRIPTION :main program file.                                    */
/*  CPU GROUP   :2A                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.18).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*																	   */
/*	Version History													   */
/*	1.02				Initial Version								   */
/*	1.03				HV anode, cathode bleeder anode, cathode	   */
/*						readings interchanged						   */
/*	1.06				updated on 14-06-2012						   */
/*						implemented filament change message for both   */
/*						short and long filament						   */
/*						message display time increased to 6000 half sec*/
/***********************************************************************/

#include "sfr_r82b.h"
#include "main.h"
#include "globals.h"
#include "allvars.h"
#include "general.h"
#include "iic.h"
#include "init.h"
#include "hvtj.h"
#include "tft.h"
#include "timer.h"
#include "uart.h"
#include "tanktest.h"
#include "cctalk.h"
#include "transactions.h"
#include "adc.h"

void main(void)
{
	unsigned int usc;
	asm("FCLR I");						// DISABLE ALL INTERRUPTS
	Initialise_Oscillator();
	Initialise_Port_Structure();
	Initialise_Port_Pins();
	TFT_ST7789_New_Init();	
	
//	Read_Driver_Info();	
//	Draw_Rectangle(60,30,120,60,YELLOW);
	Write_Center_Text(0,TFT_SIZE_X,((unsigned int)TFT_SIZE_Y / (unsigned int)2) - (unsigned int)30,&company_name[0],(unsigned far char *)&arial_narrow_bold20[0],BRIGHTBLUE,WHITE,TFT_MODE_FULL);
	Write_Center_Text(0,TFT_SIZE_X,TFT_SIZE_Y / 2,&firmware_version[0],(unsigned far char *)&arial_narrow_bold16[0],BRIGHTBLUE,WHITE,TFT_MODE_FULL);
	Write_Center_Text(0,TFT_SIZE_X,((unsigned int)TFT_SIZE_Y / (unsigned int)2) + (unsigned int)30,&model_name[0],(unsigned far char *)&arial_narrow_bold16[0],BRIGHTRED,WHITE,TFT_MODE_FULL);
	Write_Center_Text(0,TFT_SIZE_X,(unsigned int)TFT_SIZE_Y - (unsigned int)50,"Designed & Developed by",(unsigned far char *)&arial_narrow_bold12[0],BLACK,WHITE,TFT_MODE_FULL);
	Write_Center_Text(0,TFT_SIZE_X,(unsigned int)TFT_SIZE_Y - (unsigned int)30,"V-CARE ELECTRONICS",(unsigned far char *)&arial_narrow_bold12[0],BLACK,WHITE,TFT_MODE_FULL);
	Set_UART0_Port();
	Initialise_TimerA();
	Initialise_TimerD();
	Initialise_Variables();
	Get_HVT_SerialNo();
	InitialiseADC();
	asm("FSET I");			// ENABLE ALL INTERRUPTS
	Start_Watch_Dog_Timer();
	Chk_IIC_BusFree();
	Check_E2prom_Signature();
	Delay_Half_Seconds(2);
	while (true)
	{
		Main_Options_Menu();
	}
}

void Main_Options_Menu()
{
	unsigned char main_menu_no;
	unsigned char key_type_value;
	main_menu_no = 1;
	Display_Main_Menu();
	Display_Menu_Bar(main_menu_no);
	while (true)
	{
		key_type_value = Key_Type_Press_Event(KEY_TIMEOUT_CONST);
		if (key_type_value == 1)
		{
			if (main_menu_no == 1)
			{
				main_menu_no = 2;
				//Write_Text_Bar(4,98,10,TFT_SIZE_X-4,&main_menu_text[0],(unsigned far char *)&arial_narrow_bold20[0],BLACK,WHITE,TFT_MODE_FULL);
				//Write_Text_Bar(4,134,10,TFT_SIZE_X-4,&main_menu_text1[0],(unsigned far char *)&arial_narrow_bold20[0],BLACK,BRIGHTMAGENTA,TFT_MODE_FULL);
			}
			else
			{
				main_menu_no--;
				//Write_Text_Bar(4,98,10,TFT_SIZE_X-4,&main_menu_text[0],(unsigned far char *)&arial_narrow_bold20[0],BLACK,BRIGHTMAGENTA,TFT_MODE_FULL);
				//Write_Text_Bar(4,134,10,TFT_SIZE_X-4,&main_menu_text1[0],(unsigned far char *)&arial_narrow_bold20[0],BLACK,WHITE,TFT_MODE_FULL);
			}
			Display_Menu_Bar(main_menu_no);
		}
		else if (key_type_value == 2)
		{
			if (main_menu_no == 2)
			{
				main_menu_no = 1;
				//Write_Text_Bar(4,98,10,TFT_SIZE_X-4,&main_menu_text[0],(unsigned far char *)&arial_narrow_bold20[0],BLACK,BRIGHTMAGENTA,TFT_MODE_FULL);
				//Write_Text_Bar(4,134,10,TFT_SIZE_X-4,&main_menu_text1[0],(unsigned far char *)&arial_narrow_bold20[0],BLACK,WHITE,TFT_MODE_FULL);
			}
			else
			{
				main_menu_no++;
				//Write_Text_Bar(4,98,10,TFT_SIZE_X-4,&main_menu_text[0],(unsigned far char *)&arial_narrow_bold20[0],BLACK,WHITE,TFT_MODE_FULL);
				//Write_Text_Bar(4,134,10,TFT_SIZE_X-4,&main_menu_text1[0],(unsigned far char *)&arial_narrow_bold20[0],BLACK,BRIGHTMAGENTA,TFT_MODE_FULL);
			}
			Display_Menu_Bar(main_menu_no);
		}
		else if (key_type_value == 3)
		{
			switch (main_menu_no)
			{
				case 1:
					Start_New_Test();
					break;
				case 2:
					Show_All_Transactions();
					break;
			}
			Display_Main_Menu();
			Display_Menu_Bar(main_menu_no);
		}
	}
}

void Display_Main_Menu()
{
	Draw_Main_Window();
	Write_Center_Text(0,TFT_SIZE_X,5,&company_name[0],(unsigned far char *)&arial_narrow_bold24[0],BRIGHTBLUE,WHITE,TFT_MODE_FULL);
	Write_Center_Text(0,TFT_SIZE_X,40,&model_name[0],(unsigned far char *)&arial_narrow_bold16[0],BRIGHTBLUE,WHITE,TFT_MODE_FULL);
	Write_Center_Text(0,TFT_SIZE_X,80,&menu_name_text[0],(unsigned far char *)&arial_narrow_bold20[0],BROWN,WHITE,TFT_MODE_FULL);
	Display_Key_Menu();
}

void Display_Menu_Bar(unsigned char cur_menu_no)
{
	switch (cur_menu_no)
	{
		case 1:
			Write_Text_Bar(4,116,10,TFT_SIZE_X-4,&main_menu_text[0],(unsigned far char *)&arial_narrow_bold20[0],BLACK,BRIGHTMAGENTA,TFT_MODE_FULL);
			Write_Text_Bar(4,152,10,TFT_SIZE_X-4,&main_menu_text1[0],(unsigned far char *)&arial_narrow_bold20[0],BLACK,WHITE,TFT_MODE_FULL);
			break;
		default:
			Write_Text_Bar(4,116,10,TFT_SIZE_X-4,&main_menu_text[0],(unsigned far char *)&arial_narrow_bold20[0],BLACK,WHITE,TFT_MODE_FULL);
			Write_Text_Bar(4,152,10,TFT_SIZE_X-4,&main_menu_text1[0],(unsigned far char *)&arial_narrow_bold20[0],BLACK,BRIGHTMAGENTA,TFT_MODE_FULL);
			break;
	}
}
